### ISSUE TITLE
init/Kconfig:891: can't open file "kernel/oplus_cpu/sched/Kconfig"

### ISSUE THREAD

**Issue by zhaoboy9692** [OnePlusOSS/android_kernel_oneplus_sm8650#1]
init/Kconfig:891: can't open file "kernel/oplus_cpu/sched/Kconfig"

**Comment by mcxiaochenn** [comment]
我也这样，什么问题哥

**Comment by OnePlusOSSAdmin** [comment]
kernel/oplus_cpu -> ../../../vendor/oplus/kernel/cpu
请检查本地代码是否完整，代码在
https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8650
