### ISSUE TITLE
Missing drivers symlinks in the kernel tree.

### ISSUE THREAD

**Issue by Venkat3620** [OnePlusOSS/android_kernel_oneplus_sm8650#3]
Hi , @OnePlusOSSAdmin

Lots of module configs aren't defined in pineapple_GKI.config.

For example, 
fingerprint is commented out in defconfig, 
touchscreen isn't properly defined (assuming this was done in drivers/input/touchscreen, and if there is no symlink for oplus_touchscreen_v2 there, then that must be included in the touch-drivers repo).

Most of the oplus drivers like ir, oplusnetworking, drivers/soc/oplus has missing symlinks excluded as well.

**As for touchscreen, if it was built with the touch-drivers repo of Codelinaro touch-drivers, then please provide that folder too.**

out of these touchscreen modules 
oplus_bsp_tp_common.ko
oplus_bsp_tp_custom.ko
oplus_bsp_tp_notify.ko
oplus_bsp_tp_syna_common.ko
oplus_bsp_tp_tcm_S3910.ko

only oplus_bsp_tp_notify is defined in defconfig so add them to defconfig if built in drivers/input/touchscreen or push touch-drivers repo too.

as for **power/charger** modules
it seems the defconfig defined is for sm8550 ,so please recheck them and push sm8650 if its there

**It would be more helpful if you included all qcom/opensource folders too.**

here are the list of **modules that arent included in defconfig**

oplus_binder_strategy.ko
oplus_bsp_dfr_combkey_monitor.ko
oplus_bsp_dfr_dump_device_info.ko
oplus_bsp_dfr_dump_reason.ko
oplus_bsp_dfr_fdleak_check.ko
oplus_bsp_dfr_force_shutdown.ko
oplus_bsp_dfr_hung_task_enhance.ko
oplus_bsp_dfr_keyevent_handler.ko
oplus_bsp_dfr_kmsg_wb.ko
oplus_bsp_dfr_last_boot_reason.ko
oplus_bsp_dfr_phoenix.ko
oplus_bsp_dfr_pmic_monitor.ko
oplus_bsp_dfr_pmic_watchdog.ko
oplus_bsp_dfr_reboot_speed.ko
oplus_bsp_dfr_shutdown_detect.ko
oplus_bsp_dfr_shutdown_speed.ko
oplus_bsp_dfr_theia.ko
oplus_bsp_dfr_ubt.ko
oplus_bsp_game_opt.ko
oplus_bsp_ist_down.ko
oplus_bsp_ist_up.ko
oplus_bsp_memleak_detect_simple.ko
oplus_bsp_midas.ko
oplus_bsp_mxm_down.ko
oplus_bsp_mxm_up.ko
oplus_bsp_proactive_compact.ko
oplus_bsp_sigkill_diagnosis.ko
oplus_bsp_synaptics_tcm2.ko
oplus_bsp_task_load.ko
oplus_bsp_tri_key.ko
oplus_bsp_uff_fp_driver.ko
oplus_connectivity_routerboost.ko
oplus_connectivity_sla.ko
oplus_ipa_thermal.ko
oplus_locking_strategy.ko
oplus_mm_kevent_fb.ko
oplus_mm_kevent.ko
oplus_network_app_monitor.ko
oplus_network_data_module.ko
oplus_network_dns_hook.ko
oplus_network_esim.ko
oplus_network_game_first.ko
oplus_network_linkpower_module.ko
oplus_network_oem_qmi.ko
oplus_network_qr_scan.ko
oplus_network_rf_cable_monitor.ko
oplus_network_score.ko
oplus_network_sim_detect.ko
oplus_network_stats_calc.ko
oplus_network_tuning.ko
oplus_network_vnet.ko
oplus_secure_common.ko
oplus_secure_guard.ko
oplus_sensor_deviceinfo.ko
oplus_sensor_feedback.ko
oplus_sensor_interact.ko
oplus_sensor_ir_core.ko
oplus_sensor_kookong_ir_spi.ko
oplus_sys_hans.ko
oplus_wificapcenter.ko
oplus_wifi_wsa.ko

So please look into this and push necessary changes as soon as possible.

**Comment by chandu078** [comment]
Hi @OnePlusOSSAdmin,

Please check this issue and kindly push any missing changes.

**Comment by chandu078** [comment]
Hi @OnePlusOSSAdmin,

Please check this issue.

**Comment by Maitreya25** [comment]
@OnePlusOSSAdmin could you please look into these missing drivers? It's a clear violation of GPL. Crucial and necessary drivers are missing.

**Comment by chandu078** [comment]
@OnePlusOSSAdmin, please check this

**Comment by OnePlusOSSAdmin** [comment]
We'll check and fix the symlinks issue. Code under drivers/soc/oplus is released in
https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8650/tree/oneplus/sm8650_u_14.0.0_oneplus12/vendor/oplus

**Comment by Venkat3620** [comment]
@OnePlusOSSAdmin thanks for addressing symlink issue
could you please recheck in with the defconfig too
https://github.com/OnePlusOSS/android_kernel_oneplus_sm8650/blob/oneplus/sm8650_u_14.0.0_oneplus12/arch/arm64/configs/vendor/pineapple_GKI.config#L334-L338
the fingerprint module is commented out, please check other departments in the defconfig and if any changes needed push them too.

**Comment by OnePlusOSSAdmin** [comment]
@Venkat3620 Code has been updated with missing symlinks.
For uff fingerprint module, it's out of tree ko. Code is in vendor/oplus/secure/biometrics/fingerprints/bsp/uff/driver.

**Comment by han1985** [comment]
要放 就放完整。什么屁玩意。
