### ISSUE TITLE
内核编译出Image制作成boot.img，刷到一加12 无法启动。这份代码能正常刷入设备吗。

### ISSUE THREAD

**Issue by Cussrro** [OnePlusOSS/android_kernel_oneplus_sm8650#5]
手机 一加12 16+512
版本 ColorOS 14.0 版本号：14.0.0.810
内核版本 6.1.57-android14-11-o-gf91e29a33e7e

将这份代码编译后，image 刷入 手机 无法开机，这份代码正常吗？

**Comment by Cussrro** [comment]
@OnePlusOSSAdmin 麻烦跟进下 谢谢

**Comment by snowwolf725** [comment]
You need format userdata partition to boot
Some encrypt module still close source.
<img width="859" alt="微信圖片_20240229105656" src="https://github.com/user-attachments/assets/1ae2032e-a98d-47f8-8310-55ce8a56ea2b">

**Comment by Cussrro** [comment]
> 您需要格式化用户数据分区才能启动 某些加密模块仍然关闭源。 <img alt="微信图片_20240229105656" width="859" src="https://private-user-images.githubusercontent.com/447101/348469812-1ae2032e-a98d-47f8-8310-55ce8a56ea2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTY1MzAsIm5iZiI6MTcyMTE5NjIzMCwicGF0aCI6Ii80NDcxMDEvMzQ4NDY5ODEyLTFhZTIwMzJlLWE5OGQtNDdmOC04MzEwLTU1Y2U4YTU2ZWEyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwNjAzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWQ0YTY3MGFhMmMyMDQxYzRhYmY2ZjllNmNmNmY4MDE1M2Y1NGM4NDJhNmFiZmZkZjA5MDk0OWE1YzY5NWE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jdqkQGBefwLHF_5trhltjlRrcXtj8HtNE-h2FBqeMJ8">

已解决，谢谢
