### ISSUE TITLE
请更新内核代码

### ISSUE THREAD

**Issue by hanyu133341** [OnePlusOSS/android_kernel_oneplus_sm8650#9]
请更新一加12 PJD110 14.0.0.860(CN01) 内核代码

**Comment by hanyu133341** [comment]
@OnePlusOSSAdmin

**Comment by hanyu133341** [comment]
@OnePlusOSSAdmin

**Comment by athanatos1** [comment]
Source code for oneplus12 kernel 14.0 is incomplete. Please provide full kernel source code for pineapple, as well as all the necessary build scripts necessary to compile the kernel from source for oneplus12.  This is requested under general public license (GPL).

**Comment by athanatos1** [comment]
![ubuntu2004_N1H7FP0LwL](https://github.com/user-attachments/assets/bc0c959c-a6fc-403d-b2ff-04948b59e84a)

@OnePlusOSSAdmin - Please update the kernel source code for SM8650 - a14 - OnePlus12. Many source code files are missing.

**Comment by athanatos1** [comment]
@OnePlusOSSAdmin 
[****](cp: cannot stat '/home/owner/android/op12/kernel_platform/oplus/config/abi_gki_aarch64_oplus_internal': No such file or directory)

abi_gki_aarch64_oplus_internal is missing

**Comment by OnePlusOSSAdmin** [comment]
@athanatos1 abi_gki_aarch64_oplus_internal is not used for pineapple.
First we released [kernel/common](https://github.com/OnePlusOSS/android_kernel_common_oneplus_sm8650/tree/oneplus/sm8650_u_14.0.0_oneplus12) code, checkout to kernel_platform folder. Then
` ./kernel_platform/oplus/build/oplus_build_kernel.sh pineapple gki`
If there's error still, please  send detailed information to oss@oneplus.com.
